#!/bin/bash
#PBS -N linker_switch
#PBS -q testflight
#PBS -l nodes=1:ppn=1 
#PBS -l pmem=5gb
#PBS -l walltime=4:00:00
#PBS -j oe
#PBS -o iso.out

# Create a working scratch directory from current directory
cd $PBS_O_WORKDIR

python main.py run	
